### ISSUE TITLE
Menu is shown under the chat

### ISSUE THREAD

**Issue by justalemon** [TheTofuShop/Menu#1]
☁️ **what are you trying to do?**

Use the menu.

⭐ **What do you expect to happen?**

The menu is perfectly legible.

🐞 **What happens instead?**

The menu appears under the chat, so you can't see anything.

❓ **Is there something else that we need to know?**

This is an easy fix, we just need to update the `chat` and use `chat-theme-gtao` as the theme.

**Comment by TheAussie** [comment]
This issue has been resolved with the updated chat.
