### ISSUE TITLE
Add support for custom car liveries as modifications.

### ISSUE THREAD

**Issue by TheAussie** [TheTofuShop/Menu#11]
⭐ **What feature do you want to be added?**

Liveries for addon cars.

🔎 **Why do you want this feature to be added?**

To be able to use the liveries the cars come with

❓ **Is there something else that we need to know?**

No

**Comment by justalemon** [comment]
![image](https://user-images.githubusercontent.com/11861253/74887775-a9d9b280-535a-11ea-9ef0-fb1fe408c509.png)
