### ISSUE TITLE
Spawning section "Vehicles by"

### ISSUE THREAD

**Issue by Rj137** [TheTofuShop/Menu#12]
⭐ **What feature do you want to be added?**

Remove "Vehicles by" in the spawner section of the menu

🔎 **Why do you want this feature to be added?**

There is no need for "Vehicles by" when all you are doing is selecting by brand what car you want

❓ **Is there something else that we need to know?**

Nope

**Comment by justalemon** [comment]
Fun fact: This text was added a long time ago, when we had just the vehicle spawner and nothing else.

**Comment by justalemon** [comment]
![image](https://user-images.githubusercontent.com/11861253/74888948-4a7da180-535e-11ea-8e24-c6f511a60e7d.png)
