### ISSUE TITLE
Put door controls into a seperate sub menu.

### ISSUE THREAD

**Issue by Rj137** [TheTofuShop/Menu#13]
⭐ **What feature do you want to be added?**

Make the Door control a list instead of a left right select and include an open / close all feature

🔎 **Why do you want this feature to be added?**

It would make using the feature easier

❓ **Is there something else that we need to know?**

The same way tunables were changed from left arrow right arrow to a "dropdown" menu
If you could do this for signals as well that would be amazing.

**Comment by justalemon** [comment]
![image](https://user-images.githubusercontent.com/11861253/76560802-b8f6e080-6480-11ea-9dd4-db3ad7fe9546.png)
