### ISSUE TITLE
You can run over players on foot with Passive Mode enabled

### ISSUE THREAD

**Issue by justalemon** [TheTofuShop/Menu#20]
☁️ **What are you trying to do?**

Using passive mode to go thru players.

⭐ **What do you expect to happen?**

I go thru the player, like is not there at all.

🐞 **What happens instead?**

The other player ends up being ran over.

❓ **Is there something else that we need to know?**

As far as I know, this didn't happened on pre release builds of the menu.

**Comment by TheAussie** [comment]
This isn't just localised to players on foot, I was able to ram rj when I was playing, I had passive enabled, something must be happening when a new player joins.

**Comment by justalemon** [comment]
I might have fixed this, but we need to test it first.

**Comment by justalemon** [comment]
Yep, is fixed.
