### ISSUE TITLE
Sync the Blinkers to the server/Or remove option

### ISSUE THREAD

**Issue by TheAussie** [TheTofuShop/Menu#23]
⭐ **What feature do you want to be added?**

Blinkers that are synced server side

🔎 **Why do you want this feature to be added?**

So the feature is actually useful.

❓ **Is there something else that we need to know?**

There is also the option of removing it from the menu.

**Comment by justalemon** [comment]
Let's ask first: Is the blinkers option really used?

**Comment by justalemon** [comment]
Ok, @TheAussie just answered on Discord:

![image](https://user-images.githubusercontent.com/11861253/76677118-403f7380-65a9-11ea-8408-9f6e58b7ef88.png)

Little side note, I just found this from December 2018:

![image](https://user-images.githubusercontent.com/11861253/76677105-29008600-65a9-11ea-9402-7439fadf9809.png)
