### ISSUE TITLE
Add information about noclip control (Shift to change speed)

### ISSUE THREAD

**Issue by TheAussie** [TheTofuShop/Menu#24]
⭐ **What feature do you want to be added?**

Add information about noclip speed control down the bottom

![image](https://user-images.githubusercontent.com/19722293/75008285-c34e3c00-54cb-11ea-9dde-6d27e8ba11f8.png)

🔎 **Why do you want this feature to be added?**

So people know they can press shift instead of selecting it in the menu.

❓ **Is there something else that we need to know?**

Why is there a rotation speed option? Maybe there should be a hotkey for that too.

**Comment by justalemon** [comment]
>Why is there a rotation speed option?

Try to use No Clip with both Rotation and Movement to Decuple. You can see that the Movement is controllable but Rotation is not.

**Comment by justalemon** [comment]
![image](https://user-images.githubusercontent.com/11861253/75090527-86715c00-5542-11ea-8d87-0ab97f37d590.png)
