### ISSUE TITLE
Add permission for specific features on the menu(specifically for staff tools)

### ISSUE THREAD

**Issue by TheAussie** [TheTofuShop/Menu#25]
⭐ **What feature do you want to be added?**

Add permission for specific features on the menu, like kick, ban

🔎 **Why do you want this feature to be added?**

So moderators can't ban people.

❓ **Is there something else that we need to know?**

No.

**Comment by justalemon** [comment]
> So moderators can't ban people.

This sounds like shitposting to me.

In a serious note, isn't this one of the tools needed by moderators? Why would this be disabled for them?

**Comment by TheAussie** [comment]
Ok let me specify, we are going to have a Trial Moderator Role, they aren't the same as regular moderator.

**Comment by justalemon** [comment]
Now it makes sense.

I really have problems when you create issues, as you usually don't explain the entire thing at once.

**Comment by justalemon** [comment]
I have moved some ACL Permissions from general roles (`lemonmenu:mod`) to specific values (`lemonmenu:ban` and `lemonmenu:kick` for example).
