### ISSUE TITLE
FC no mods

### ISSUE THREAD

**Issue by Jinxmaster1** [TheTofuShop/Menu#28]
☁️ **what are you trying to do?**

Mod the fc

⭐ **What do you expect to happen?**

There to be lists of cosmetic and performance mods

🐞 **What happens instead?**

Lists are empty (nothing in spoilers,engine, suspension etc)

❓ **Is there something else that we need to know?**

[Replace me]

**Comment by TheAussie** [comment]
You tried clicking refresh in the list?

**Comment by justalemon** [comment]
Duplicated of #22
