### ISSUE TITLE
Show the names above the player heads

### ISSUE THREAD

**Issue by Rj137** [TheTofuShop/Menu#3]
⭐ **What feature do you want to be added?**

The names above the player heads, like Mello.

🔎 **Why do you want this feature to be added?**

So we can see who is ramming people if they do ram.

❓ **Is there something else that we need to know?**

No.

**Comment by TheAussie** [comment]
You haven't explained if this feature has been added to the menu or not.

You just closed the issue with no explanation.

This feature should be added and not marked as a 3rd party problem.

**Comment by justalemon** [comment]
When this issue was created, we were using the mello player names. We started using the playernames resources and this issue got closed.

If you want something to be changed, open a new issue. Reopening this one also reopened the 1.0 milestone.
