### ISSUE TITLE
Preload collisions before teleporting to another area (so we don't fall under the map)

### ISSUE THREAD

**Issue by justalemon** [TheTofuShop/Menu#30]
⭐ **What feature do you want to be added?**

Preload collisions before teleporting to another area like from Akina to Gunsai.

🔎 **Why do you want this feature to be added?**

![image](https://user-images.githubusercontent.com/11861253/75103731-938f5900-55dd-11ea-9131-817809349df5.png)

❓ **Is there something else that we need to know?**

We should try to use the spawnmanager exports.

**Comment by mPrism** [comment]
Bonus suggestion, not sure if possible but make some sort of period of time where the cars dont collide with eachother after a teleport, so teleporting doesnt fuck with someone elses run.

**Comment by justalemon** [comment]
Honestly, the teleports should not mess with runs in the first place.

If the teleports do mess with the races, they need to be changed.

**Comment by TheAussie** [comment]
> Honestly, the teleports should not mess with runs in the first place.
> 
> If the teleports do mess with the races, they need to be changed.

I believe he is talking about teleporting to people, which isn't even relevant to this topic.

**Comment by mPrism** [comment]
> > Honestly, the teleports should not mess with runs in the first place.
> > If the teleports do mess with the races, they need to be changed.
> 
> I believe he is talking about teleporting to people, which isn't even relevant to this topic.

It's not? It says "Preload the map collisions before teleporting someone via the menu" which is why I assumed the topic was teleporting to people

**Comment by TheAussie** [comment]
> > > Honestly, the teleports should not mess with runs in the first place.
> > > If the teleports do mess with the races, they need to be changed.
> > 
> > 
> > I believe he is talking about teleporting to people, which isn't even relevant to this topic.
> 
> It's not? It says "Preload the map collisions before teleporting someone via the menu" which is why I assumed the topic was teleporting to people

No, just map teleport menu.

**Comment by justalemon** [comment]
Is between maps. I have edited the title and main issue to explain it better.
