### ISSUE TITLE
Scrolling QoA

### ISSUE THREAD

**Issue by SiirToast** [TheTofuShop/Menu#4]
⭐ **What feature do you want to be added?**

Reduce the speed of the scrolling and make it so when you get in a category and get out of it you don't have to start at the beginning of the list.

🔎 **Why do you want this feature to be added?**

To improve quality of life

❓ **Is there something else that we need to know?**

no

**Comment by Rj137** [comment]
mello would not let you auto scroll so maybe make it not auto scroll instead of tweaking the scroll ?

**Comment by justalemon** [comment]
You have 2 requests in a single issue, please create an issue for each.

**Comment by SiirToast** [comment]
> You have 2 requests in a single issue, please create an issue for each.

The issue is improvement in the Quality of Life department of the scrolling category, which are in the same department.

**Comment by justalemon** [comment]
> make it so when you get in a category and get out of it you don't have to start at the beginning of the list

This is a problem with certain menus. If is still present, open an issue for it.

**Comment by justalemon** [comment]
> Reduce the speed of the scrolling

Sadly, this is not possible. NativeUI uses the control system provided by Rockstar.
