### ISSUE TITLE
Inverse Power no longer works after dying

### ISSUE THREAD

**Issue by Humrss2k** [TheTofuShop/Menu#40]
☁️ **What are you trying to do?**

Use IP after dying and reviving myself by using a custom player model.

⭐ **What do you expect to happen?**

It works correctly.

🐞 **What happens instead?**

It stops working.

❓ **Is there something else that we need to know?**

https://www.youtube.com/watch?v=EmYTrE4LuXc

**Comment by justalemon** [comment]
I feel that this is related to #41 

![image](https://user-images.githubusercontent.com/11861253/77232505-3062f900-6b80-11ea-9602-163a3f4644be.png)

**Comment by justalemon** [comment]
Fixed after working on #41
