### ISSUE TITLE
Add Speedometer

### ISSUE THREAD

**Issue by TheAussie** [TheTofuShop/Menu#42]
⭐ **What feature do you want to be added?**

Add a working speedometer that has skins and is able to be toggled on and off in the menu
🔎 **Why do you want this feature to be added?**

The current one is broken, and i think reducing the number of running scripts would be better.

❓ **Is there something else that we need to know?**

No.

**Comment by justalemon** [comment]
This would be a separate script instead of part of the menu.

**Comment by TheAussie** [comment]
> This would be a separate script instead of part of the menu.

Why though?

**Comment by justalemon** [comment]
Why no? It is a completely different thing.

**Comment by TheAussie** [comment]
well at the moment, ther original one is turned off, because it is broken.

**Comment by TheAussie** [comment]
Speedometer is working again.
