### ISSUE TITLE
Animations and setting for car despawn

### ISSUE THREAD

**Issue by Humrss2k** [TheTofuShop/Menu#44]
⭐ **What feature do you want to be added?**

Would be nice to have animations and setting where you can set time till ur car despawns

🔎 **Why do you want this feature to be added?**

Some creative pictures 

❓ **Is there something else that we need to know?**

Nah

**Comment by justalemon** [comment]
> setting for car despawn

Fixed as part of #7.

> Animations

I think that this is already implemented on the server via commands. @Rj137 explained it on the #general-suggestions channel:

![image](https://user-images.githubusercontent.com/11861253/80896218-3b9a6000-8cba-11ea-88cc-d5d3f7921d13.png)

**Comment by Humrss2k** [comment]
Oh oke but i mean the car despawn so player can se the time till his car despawns so we can acculy do shit with them cars

**Comment by justalemon** [comment]
There is no timer, you just need to stay close to the vehicle.

**Comment by Humrss2k** [comment]
Thats a good shit i like that a lot
