### ISSUE TITLE
Add window tint

### ISSUE THREAD

**Issue by TheAussie** [TheTofuShop/Menu#45]
⭐ **What feature do you want to be added?**

Window tint

🔎 **Why do you want this feature to be added?**

Because it doesn't exist in the menu

❓ **Is there something else that we need to know?**

It should have been amongst the tuning.

**Comment by justalemon** [comment]
![image](https://user-images.githubusercontent.com/11861253/80871345-00783c80-8c7a-11ea-8e25-d35799f67a7c.png)
