### ISSUE TITLE
Turn Signals

### ISSUE THREAD

**Issue by Rj137** [TheTofuShop/Menu#49]
⭐ **What feature do you want to be added?**

Server Sync turn signals with hotkeys for left and right on the left and right arrow keys

🔎 **Why do you want this feature to be added?**

It makes showing whether you are wanting to do a run or not much easier, especially with names disabled since you cant just tell someone in chat since you don't know who they are.

❓ **Is there something else that we need to know?**

Pls lemon senpai

**Comment by justalemon** [comment]
![indicator](https://user-images.githubusercontent.com/11861253/80895113-3e438800-8caf-11ea-8abb-65094575e588.PNG)
