### ISSUE TITLE
Turning signals 

### ISSUE THREAD

**Issue by mpjjy** [TheTofuShop/Menu#50]
⭐ **What feature do you want to be added?**

Car Indicators / Turning Signals

🔎 **Why do you want this feature to be added?**

So people don’t honk or rev at drivers who are parked. This can get annoying, and also for added realism.

❓ **Is there something else that we need to know?**

This is just something I want in the server, no one else does though.

**Comment by justalemon** [comment]
This was already requested in #49 a couple of minutes ago.
