### ISSUE TITLE
Car engine/lights 

### ISSUE THREAD

**Issue by Humrss2k** [TheTofuShop/Menu#52]
⭐ **What feature do you want to be added?**

Setting for engine/lights of the car to stay on even when is no one inside 

🔎 **Why do you want this feature to be added?**

Only one reason and thats is we could do some fucking epic moment photos

❓ **Is there something else that we need to know?**

<3 Lemon <3
(nohomo)

**Comment by justalemon** [comment]
For this one, I took it from Grand Theft Auto IV.

If you **press** `F` / ![Triangle](https://user-images.githubusercontent.com/11861253/82070920-649bf700-96a3-11ea-9876-2db185a41fc1.png) / ![Y](https://user-images.githubusercontent.com/11861253/82070992-79788a80-96a3-11ea-9062-4fc5f2a64e0d.png), you leave the vehicle and it stays on. If you **keep pressed** for 1s, you leave the vehicle and is turned off.
