### ISSUE TITLE
Disable chat message saying someone went to a map

### ISSUE THREAD

**Issue by doctorluke26** [TheTofuShop/Menu#54]
⭐ **What feature do you want to be added?**

To be able to disable the feature of where it shows where people are going 

🔎 **Why do you want this feature to be added?**

Because theres no cooldown and can be spammed to point where you can click it 5 times and covers entire chat.

![LEMON BUG](https://user-images.githubusercontent.com/60555996/81738431-9d648200-9491-11ea-8ada-31a1c38acc02.PNG)

❓ **Is there something else that we need to know?**

no

**Comment by Rj137** [comment]
I agree, this is a dumb feature that doesn't make sense anyways.
people always just say that they're going to a certain track when they do switch.

**Comment by Jinxmaster1** [comment]
Replace it by instead listing the most recent teleport in the trainer's player list.
