### ISSUE TITLE
Ability to hide the minimap

### ISSUE THREAD

**Issue by Rj137** [TheTofuShop/Menu#56]
⭐ **What feature do you want to be added?**

option to hide minimap

🔎 **Why do you want this feature to be added?**

for non rockstar editor screenshots

❓ **Is there something else that we need to know?**

no

**Comment by doctorluke26** [comment]
Also stop distractions like seeing people noclip above you if you are racing someone

**Comment by justalemon** [comment]
![image](https://user-images.githubusercontent.com/11861253/81894801-b26b0f00-957e-11ea-8f98-77fa1724ff7d.png)
