### ISSUE TITLE
Inverse power toggle

### ISSUE THREAD

**Issue by Rj137** [TheTofuShop/Menu#6]
⭐ **What feature do you want to be added?**

Ability to toggle inverse power in the menu

🔎 **Why do you want this feature to be added?**

Testing purposes and some people prefer to play with it off

❓ **Is there something else that we need to know?**

If there is already a way to disable it we can tell people that way how instead of implementing this feature

**Comment by justalemon** [comment]
Vehicle options.

![image](https://user-images.githubusercontent.com/11861253/74595271-54319d00-501e-11ea-95ab-64444d52ac0c.png)
