### ISSUE TITLE
Can't TP to other maps 

### ISSUE THREAD

**Issue by doctorluke26** [TheTofuShop/Menu#61]
☁️ **What are you trying to do?**

TP to other maps like Tsuchisaka

⭐ **What do you expect to happen?**

TP to that map

🐞 **What happens instead?**

It says this 
![image](https://user-images.githubusercontent.com/60555996/82091575-84590c80-96ef-11ea-9a1d-50a5a5639a68.png)

❓ **Is there something else that we need to know?**

Its also happening to me and Kozzren, I'm not sure about other people but it seems i can only go on the maps i tp to when i first join - EDIT: Also happening to everyone else

**Comment by TheAussie** [comment]
Could you possibly tell me which maps? Could maybe set the z coord a little higher, might fix it.

**Comment by doctorluke26** [comment]
It's pretty much all the maps apart from AkinaV, Tsuchisaka, Usui V1 and the track you first spawn it.

**Comment by TheAussie** [comment]
> It's pretty much all the maps apart from AkinaV, Tsuchisaka, Usui V1 and the track you first spawn it.

Ok, I'll do some testing

**Comment by justalemon** [comment]
I use [GET_GROUND_Z_FOR_3D_COORD](https://runtime.fivem.net/doc/natives/?_0xC906A7DAB05C8D2B) to check if there is a valid location around the area. The function returns true if an appropriate Z coordinate was found, and false if not.

The script shows the message if it was unable to find a location for 5 seconds. There are some locations that are slightly under the map, so 1000 units are added to compensate for this.

```cs
// Request the collisions
API.RequestCollisionAtCoord(location.X, location.Y, location.Z);

// Save the time of when we should stop
int time = API.GetGameTimer() + 5000;
// Create a new Z that is 1000 units higher and a place to store the temp coord
float newz = location.Z + 1000;
float coord = 0;
// And start checking for the collisions
while (!API.GetGroundZFor_3dCoord(location.X, location.Y, newz, ref coord, false))
{
    // If the current time is higher or equal than the time when we should stop
    // Notify the user that we failed and return
    if (API.GetGameTimer() >= time)
    {
        Screen.ShowNotification($"Unable to load the collisions on the destination of the Teleport.");
        return;
    }
    // Otherwise, wait until the next check
    await BaseScript.Delay(100);
}
```

**Comment by TheAussie** [comment]
> I use [GET_GROUND_Z_FOR_3D_COORD](https://runtime.fivem.net/doc/natives/?_0xC906A7DAB05C8D2B) to check if there is a valid location around the area. The function returns true if an appropriate Z coordinate was found, and false if not.
> 
> The script shows the message if it was unable to find a location for 5 seconds. There are some locations that are slightly under the map, so 1000 units are added to compensate for this.
> 
> ```cs
> // Request the collisions
> API.RequestCollisionAtCoord(location.X, location.Y, location.Z);
> 
> // Save the time of when we should stop
> int time = API.GetGameTimer() + 5000;
> // Create a new Z that is 1000 units higher and a place to store the temp coord
> float newz = location.Z + 1000;
> float coord = 0;
> // And start checking for the collisions
> while (!API.GetGroundZFor_3dCoord(location.X, location.Y, newz, ref coord, false))
> {
>     // If the current time is higher or equal than the time when we should stop
>     // Notify the user that we failed and return
>     if (API.GetGameTimer() >= time)
>     {
>         Screen.ShowNotification($"Unable to load the collisions on the destination of the Teleport.");
>         return;
>     }
>     // Otherwise, wait until the next check
>     await BaseScript.Delay(100);
> }
> ```

This may have something to do with the invalid poly edge issue, I'll look into it

**Comment by justalemon** [comment]
This has been fixed. I'm waiting for aussie to deploy the fixed version.

**Comment by TheAussie** [comment]
already have
