### ISSUE TITLE
door control open and close all

### ISSUE THREAD

**Issue by Rj137** [TheTofuShop/Menu#63]
⭐ **What feature do you want to be added?**

an open all and close all button in the doors control menu

🔎 **Why do you want this feature to be added?**

so it is easier to check out the visuals of a model

❓ **Is there something else that we need to know?**

no

**Comment by justalemon** [comment]
![image](https://user-images.githubusercontent.com/11861253/82737551-cd1c5100-9cff-11ea-9bec-86071f1570c0.png)
