### ISSUE TITLE
Player List Not updating properly

### ISSUE THREAD

**Issue by TheAussie** [TheTofuShop/Menu#65]
☁️ **What are you trying to do?**

Get the correct player in the list

⭐ **What do you expect to happen?**

The correct player name to show

🐞 **What happens instead?**

The names in the list donot update to the new names.

❓ **Is there something else that we need to know?**

This has been happening for a while, im suprized noone made a  bug report.

**Comment by justalemon** [comment]
When you select Refresh in the player list, are they updated correctly or not?

**Comment by TheAussie** [comment]
> When you select Refresh in the player list, are they updated correctly or not?

They aren't, you could select my name in the list and it would be a different person.

**Comment by justalemon** [comment]
So, the name of the player is correct but the description is not. Correct?

**Comment by TheAussie** [comment]
> So, the name of the player is correct but the description is not. Correct?

Let's say you select my name in the list, in the description it would day doctorluke26 as an example, instead of me.
