### ISSUE TITLE
Cars Despawn the second the player exits the car.

### ISSUE THREAD

**Issue by mpjjy** [TheTofuShop/Menu#66]
☁️ **What are you trying to do?**

Have my car stay after I exit it

⭐ **What do you expect to happen?**

The car to stay, as I’m standing right next to it

🐞 **What happens instead?**

It despawns the second my character gets out

❓ **Is there something else that we need to know?** Not really.

[Replace me]

**Comment by justalemon** [comment]
There is a 3rd party resource installed that does this. I have been unable to find it so I notified @TheAussie because he might know what resource it is.

**Comment by justalemon** [comment]
This appears to be resolved.
