### ISSUE TITLE
Licence plate styles

### ISSUE THREAD

**Issue by TheAussie** [TheTofuShop/Menu#69]
⭐ **What feature do you want to be added?**

Ability to change Licence plate styles

🔎 **Why do you want this feature to be added?**

To change my licence plate frame

❓ **Is there something else that we need to know?**

No

**Comment by justalemon** [comment]
![image](https://user-images.githubusercontent.com/11861253/82740384-43c44900-9d16-11ea-9b70-2e84fa0df788.png)
