### ISSUE TITLE
Vehicles stay in game after someone disconnects

### ISSUE THREAD

**Issue by Rj137** [TheTofuShop/Menu#7]
☁️ **what are you trying to do?**

Drive on a road with passive mode on and then someone in front disconnects

⭐ **What do you expect to happen?**

To pass through the persons car as it is still invisible 

🐞 **What happens instead?**

Their car becomes rock solid and does not move when it is hit causing you to come to a complete halt as if you hit a brick wall.

❓ **Is there something else that we need to know?**

no

**Comment by Rj137** [comment]
to add to it, after a person leaves, their npc is still there in the road and does not get deleted.

maybe make a disconnected person's car and ped delete as soon as they leave ?

**Comment by justalemon** [comment]
When a player leaves, we can't get the Ped, Vehicle or even the last known position of the player. Once I have some time, I'm going to update the Main FiveM server with the vanilla resources.

**Comment by justalemon** [comment]
All of the vehicles spawned via the menu are now marked as no longer needed, so the game despawns the vehicles when no players are near.

This should delete them after the player leaves, as long as it was created from the menu or the `/spawn <model>` command.
