### ISSUE TITLE
Xenon lights default to on

### ISSUE THREAD

**Issue by Rj137** [TheTofuShop/Menu#71]
☁️ **What are you trying to do?**

spawn my car

⭐ **What do you expect to happen?**

for it to spawn with the normal lights, non xenon

🐞 **What happens instead?**

even when overwritten with a save that has normal lights, they turn xenon when spawned from the saves menu

❓ **Is there something else that we need to know?**

no

**Comment by Bluethefurry** [comment]
This was discussed internally before, the Xenon Native accepts a `-1` Value to turn off the Xenons, but returns 0 ( which is the default xenon ) if the xenon lights are off, i would consider this a "cant fix", but there may be ways to work around it.

I'll see if there's a way around that issue when i have time.
