### ISSUE TITLE
Vehicle Storage: Performance Parts dont save Properly

### ISSUE THREAD

**Issue by Bluethefurry** [TheTofuShop/Menu#72]
☁️ **What are you trying to do?**

Performance parts of vehicles, excluding Turbos, don't seem to work correctly, I've taken a look at the code and it should work fine in theory, the getting seems to work, but i can't test the loading sadly :/

⭐ **What do you expect to happen?**

The vehicle will have the appropriate engine, brake and suspension mods

🐞 **What happens instead?**

The default options will be set

❓ **Is there something else that we need to know?**

Teach me how to properly set up a lemon menu test env pls :)

**Comment by Bluethefurry** [comment]
Update: upon replicating the issue i've made an.. interesting find, upon spawning the car, the mods do get set absolutely correctly, however, they don't seem to actually apply to the vehicle, running GetVehicleMod shortly afterwards even returns the correct mod, so it might only apply during that tick? I have no idea why it would reset though, tried delaying setting the mod to no avail.

**Comment by justalemon** [comment]
This has been fixed.
