### ISSUE TITLE
Tuning Menu supposedly crashes menu

### ISSUE THREAD

**Issue by TheAussie** [TheTofuShop/Menu#75]
☁️ **What are you trying to do?**

Use the tuning Menu.

⭐ **What do you expect to happen?**

I expect it to work

🐞 **What happens instead?**

This one is from jinx

>I think the new menu is not working quite right for me

>If I open up the tuning menu and then go into a performance option (engine, trans etc) then go out of that menu then back in it says "no items available" and stops responding to any inputs I try (can't close the menu, go back or anything)

❓ **Is there something else that we need to know?**

Vehicle paint menu is also missing.

**Comment by justalemon** [comment]
The most important question: Are there any errors printed to the console?

**Comment by TheAussie** [comment]
As stated in discord... This is what is in the console

`@lemon [    157328] [    GTAProcess]             MainThrd/ Parameter name: index

[    157328] [    GTAProcess]             MainThrd/   at System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) [0x00029] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[    157328] [    GTAProcess]             MainThrd/   at System.ThrowHelper.ThrowArgumentOutOfRangeException () [0x00000] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[    157328] [    GTAProcess]             MainThrd/   at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x00009] in <74fbbe963b7e417b8d715b858c5c584f>:0 

[    157328] [    GTAProcess]             MainThrd/   at LemonUI.Menus.NativeMenu.get_SelectedItem () [0x0000f] in D:\Proyectos\The Tofu Shop\LemonMenu\LemonUI\LemonUI\Menus\NativeMenu.cs:391 

[    157328] [    GTAProcess]             MainThrd/   at LemonUI.Menus.NativeMenu.Draw () [0x000d4] in D:\Proyectos\The Tofu Shop\LemonMenu\LemonUI\LemonUI\Menus\NativeMenu.cs:1068 

[    157328] [    GTAProcess]             MainThrd/   at LemonUI.Menus.NativeMenu.Process () [0x0002c] in D:\Proyectos\The Tofu Shop\LemonMenu\LemonUI\LemonUI\Menus\NativeMenu.cs:1227 

[    157328] [    GTAProcess]             MainThrd/   at LemonUI.ObjectPool.Process () [0x00022] in D:\Proyectos\The Tofu Shop\LemonMenu\LemonUI\LemonUI\ObjectPool.cs:274 

[    157328] [    GTAProcess]             MainThrd/   at LemonMenu.Client.ScriptMenu+<HandleMenu>d__26.MoveNext () [0x00038] in D:\Proyectos\The Tofu Shop\LemonMenu\LemonMenu.Client\ScriptMenu.cs:278 
[    157344] [    GTAProcess]             MainThrd/ 
[    157359] [    GTAProcess]             MainThrd/ Failed to run a tick for ScriptMenu: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.

[    157375] [    GTAProcess]             MainThrd/ Parameter name: index`

**Comment by justalemon** [comment]
This was fixed in https://github.com/justalemon/LemonUI/commit/065952ffcd82e80437a332a4e8c900f396c539e9, I still need to update the version used on the menu itself.
