### ISSUE TITLE
Change Plate text

### ISSUE THREAD

**Issue by TofuCook** [TheTofuShop/Menu#8]
⭐ **What feature do you want to be added?**

Change Plate text

🔎 **Why do you want this feature to be added?**

That way i can put BAGUETTE on my plate.

❓ **Is there something else that we need to know?**

It was a feature before

**Comment by justalemon** [comment]
![image](https://user-images.githubusercontent.com/11861253/74595404-afb05a80-501f-11ea-96a2-9987c060ac62.png)
