### ISSUE TITLE
Allow users to spectate other users

### ISSUE THREAD

**Issue by TofuCook** [TheTofuShop/Menu#9]
⭐ **What feature do you want to be added?**

The ability to spectate players

🔎 **Why do you want this feature to be added?**

Cause if you want to watch somebody drive, you have to get in their car without the spec mode, that affect handling. Plus for races, people might want to watch, same for referees.

❓ **Is there something else that we need to know?**

It was a feature before.

**Comment by justalemon** [comment]
I didn't know that this could be made so easy, we just need to call `NetworkSetInSpectatorMode(bool toggle, Ped playerPed)`.

**Comment by justalemon** [comment]
I tested this with @TofuCook and it works.
